export enum MailTypeEnum {
    SEND_VERIFICATION = 'SEND_VERIFICATION',
    FORGOT_PASSWORD_VERIFICATION = 'FORGOT_PASSWORD_VERIFICATION',
    TEST_EMAIL = 'TEST_EMAIL',
    RESET_PASSWORD = 'RESET_PASSWORD',
    SIGN_UP_INVITATION = 'SIGN_UP_INVITATION',
    ORG_ADDED_NOTIFICATION = 'ORG_ADDED_NOTIFICATION',
}
