server:
    port: 3000
    hostedDomain: 'localhost:3000'
    saltSecret: '$2b$10$eT54LKqpPRy4uZrsXrs8O.'

db:
  uri: mongodb+srv://buwa26889:fyp@cluster0.tmbq7fs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

aws:
    region: 'ap-southeast-1'
    accessKeyId: ''
    secretAccessKey: ''
    s3Bucket: ''

lakeraGuard:
    apiKey: '33797bdfd00edc90d3d952859d488150225d83bdc409f45704892b5a2538a6ad'

google:
    clientId: '209610564722-q116gajb7ei7spl3uglvfqigffk6jcv3.apps.googleusercontent.com'
    clientSecret: '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'
    redirectUri: 'http://localhost:4001/auth/google/callback'

fastAPI:
    url: 'https://fastapi-rag-service-iuxrsvfyvq-uc.a.run.app'

email:
    smtpHost: 'smtp.gmail.com'
    smtpPort: 465
    smtpUser: 'buwa26889@gmail.com'
    smtpPass: 'zgvz nsay xbxt lfbw'

redis:
    username: "default"
    password: "KB2HOlkwVHDGJw9evaBSdsKtDPrCh6iP"
    host: "redis-13852.c92.us-east-1-3.ec2.redns.redis-cloud.com"
    port: 13852

agents:
    customerAgent: 'https://fastapi-rag-service-iuxrsvfyvq-uc.a.run.app/v1/qna'
    businessAgent: 'https://fastapi-rag-service-iuxrsvfyvq-uc.a.run.app/v1/businesses/update'
